//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace ShippingAPR.App.Resources;

using System.Globalization;
using System.Resources;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[System.Diagnostics.DebuggerNonUserCode()]
[System.Runtime.CompilerServices.CompilerGenerated()]
public class Strings
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Strings() { }

    /// <summary>Returns the cached ResourceManager instance used by this class.</summary>
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
    public static ResourceManager ResourceManager
    {
        get
        {
            if (resourceMan is null)
            {
                var temp = new ResourceManager("ShippingAPR.App.Resources.Strings", typeof(Strings).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>Overrides the current thread's CurrentUICulture for all resource lookups.</summary>
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
    public static CultureInfo? Culture
    {
        get { return resourceCulture; }
        set { resourceCulture = value; }
    }

    private static string GetString(string name) =>
        ResourceManager.GetString(name, resourceCulture) ?? name;

    // App
    public static string AppTitle => GetString("AppTitle");
    public static string AppName => GetString("AppName");
    public static string AppSubtitle => GetString("AppSubtitle");

    // Navigation
    public static string Search => GetString("Search");
    public static string VesselList => GetString("VesselList");
    public static string Filters => GetString("Filters");
    public static string Details => GetString("Details");
    public static string Settings => GetString("Settings");

    // Map
    public static string SelectArea => GetString("SelectArea");
    public static string ClearSelection => GetString("ClearSelection");
    public static string DrawAreaHint => GetString("DrawAreaHint");

    // Vessel Info
    public static string VesselName => GetString("VesselName");
    public static string MMSI => GetString("MMSI");
    public static string IMO => GetString("IMO");
    public static string CallSign => GetString("CallSign");
    public static string VesselType => GetString("VesselType");
    public static string Flag => GetString("Flag");
    public static string Speed => GetString("Speed");
    public static string Course => GetString("Course");
    public static string Heading => GetString("Heading");
    public static string Destination => GetString("Destination");
    public static string Status => GetString("Status");
    public static string Length => GetString("Length");
    public static string Beam => GetString("Beam");
    public static string Draught => GetString("Draught");

    // ETA
    public static string ETA => GetString("ETA");
    public static string Distance => GetString("Distance");
    public static string TimeToArrival => GetString("TimeToArrival");
    public static string EffectiveSpeed => GetString("EffectiveSpeed");
    public static string CourseDeviation => GetString("CourseDeviation");
    public static string Stationary => GetString("Stationary");
    public static string UnknownDestination => GetString("UnknownDestination");

    // Filters
    public static string AllTypes => GetString("AllTypes");
    public static string Cargo => GetString("Cargo");
    public static string Tanker => GetString("Tanker");
    public static string Passenger => GetString("Passenger");
    public static string Fishing => GetString("Fishing");
    public static string TugPilot => GetString("TugPilot");
    public static string Other => GetString("Other");
    public static string MinSpeed => GetString("MinSpeed");
    public static string MaxSpeed => GetString("MaxSpeed");

    // Status Bar
    public static string Connected => GetString("Connected");
    public static string Disconnected => GetString("Disconnected");
    public static string Connecting => GetString("Connecting");
    public static string Reconnecting => GetString("Reconnecting");
    public static string Ships => GetString("Ships");
    public static string Area => GetString("Area");

    // Welcome
    public static string WelcomeTitle => GetString("WelcomeTitle");
    public static string WelcomeStep1 => GetString("WelcomeStep1");
    public static string WelcomeStep1Desc => GetString("WelcomeStep1Desc");
    public static string WelcomeStep2 => GetString("WelcomeStep2");
    public static string WelcomeApiKeyPlaceholder => GetString("WelcomeApiKeyPlaceholder");
    public static string TestConnection => GetString("TestConnection");
    public static string GetStarted => GetString("GetStarted");
    public static string ConnectionSuccess => GetString("ConnectionSuccess");
    public static string ConnectionFailed => GetString("ConnectionFailed");
    public static string ApiKeyRequired => GetString("ApiKeyRequired");

    // Notifications
    public static string VesselEnteredArea => GetString("VesselEnteredArea");
    public static string VesselLeftArea => GetString("VesselLeftArea");

    // Units
    public static string Knots => GetString("Knots");
    public static string NauticalMiles => GetString("NauticalMiles");
    public static string Degrees => GetString("Degrees");
    public static string Meters => GetString("Meters");

    // Theme
    public static string DarkTheme => GetString("DarkTheme");
    public static string LightTheme => GetString("LightTheme");
    public static string Language => GetString("Language");

    // UI Labels
    public static string ToggleLanguageTooltip => GetString("ToggleLanguageTooltip");
    public static string ToggleThemeTooltip => GetString("ToggleThemeTooltip");
    public static string StartTracking => GetString("StartTracking");
    public static string NoApiKeyWarning => GetString("NoApiKeyWarning");
    public static string AddApiKey => GetString("AddApiKey");
    public static string Dismiss => GetString("Dismiss");
    public static string SelectVesselHint => GetString("SelectVesselHint");
    public static string SelectVesselSubHint => GetString("SelectVesselSubHint");
    public static string Legend => GetString("Legend");
    public static string TugPilotShort => GetString("TugPilotShort");
    public static string AreaSelectionHint => GetString("AreaSelectionHint");
    public static string VesselTypes => GetString("VesselTypes");
    public static string SpeedRange => GetString("SpeedRange");
    public static string Identity => GetString("Identity");
    public static string Navigation => GetString("Navigation");
    public static string VoyageEta => GetString("VoyageEta");
    public static string Dimensions => GetString("Dimensions");
    public static string Position => GetString("Position");
    public static string Size => GetString("Size");
    public static string LastUpdate => GetString("LastUpdate");
    public static string CourseDev => GetString("CourseDev");
    public static string Europe => GetString("Europe");
    public static string Asia => GetString("Asia");
    public static string Americas => GetString("Americas");
    public static string Global => GetString("Global");
    public static string Error => GetString("Error");
    public static string ZoomIn => GetString("ZoomIn");
    public static string ZoomOut => GetString("ZoomOut");

    // Window Controls
    public static string Minimize => GetString("Minimize");
    public static string Maximize => GetString("Maximize");
    public static string Close => GetString("Close");

    // Empty State
    public static string NoVesselsFound => GetString("NoVesselsFound");
    public static string AdjustFiltersHint => GetString("AdjustFiltersHint");

    // Export
    public static string Export => GetString("Export");
    public static string ExportCsv => GetString("ExportCsv");
    public static string ExportJson => GetString("ExportJson");

    // Settings
    public static string SettingsTitle => GetString("SettingsTitle");
    public static string ApiKeySection => GetString("ApiKeySection");
    public static string ThemeSection => GetString("ThemeSection");
    public static string About => GetString("About");
    public static string Version => GetString("Version");

    // Keyboard Shortcuts
    public static string KeyboardShortcuts => GetString("KeyboardShortcuts");
    public static string ShortcutSearch => GetString("ShortcutSearch");
    public static string ShortcutExport => GetString("ShortcutExport");
    public static string ShortcutHelp => GetString("ShortcutHelp");
    public static string ShortcutEscape => GetString("ShortcutEscape");

    public static string Dashboard => GetString("Dashboard");
    public static string TotalVessels => GetString("TotalVessels");
    public static string ByType => GetString("ByType");
    public static string NavigationStatus => GetString("NavigationStatus");
    public static string UnderWay => GetString("UnderWay");
    public static string AtAnchor => GetString("AtAnchor");
    public static string Moored => GetString("Moored");
    public static string AvgSpeed => GetString("AvgSpeed");
    public static string Watched => GetString("Watched");
    public static string TopDestinations => GetString("TopDestinations");
    public static string FleetEmissions => GetString("FleetEmissions");
    public static string TotalCo2 => GetString("TotalCo2");
    public static string TotalFuel => GetString("TotalFuel");
    public static string VesselsMeasured => GetString("VesselsMeasured");
    public static string HighestEmitter => GetString("HighestEmitter");
    public static string CleanestVessel => GetString("CleanestVessel");
    public static string VesselSpotlight => GetString("VesselSpotlight");
}
